Language: 'english'
WordFilter:
- arschloch
- asshole
Is_Scc_On_Spigot: 'false'
Denizen_Active: 'false'
AddingTimeOfDays: 'true'
TimeOfDaysFormat: 'HH:mm'
TimeOfDaysOutput: '&7[%time%] &r'
UsePrefixForPlayerColor: 'true'
ShowJoinMessageGlobal: 'false'
ShowLeaveMessageGlobal: 'false'
Mysql:
  Status: 'false'
  Host: '127.0.0.1'
  Port: '3306'
  DatabaseName: 'mydatabase'
  SSLEnabled: 'false'
  AutoReconnect: 'true'
  VerifyServerCertificate: 'false'
  User: 'admin'
  Password: 'not_0123456789'
  TableNameI: 'simplechatchannelsPlayerData'
  TableNameII: 'simplechatchannelsIgnorelist'
