language: 'english'
wordfilter:
- arschloch
- asshole
is_scc_on_spigot: 'false'
denizen_active: 'false'
addingtimeofdays: 'true'
timeofdaysformat: 'HH:mm'
timeofdaysoutput: '&7[%time%] '
mysql:
  status: 'false'
  host: '127.0.0.1'
  port: '3306'
  databaseName: 'mydatabase'
  sslEnabled: 'false'
  autoReconnect: 'true'
  verifyServerCertificate: 'false'
  user: 'admin'
  password: 'not_0123456789'
  tableNameI: 'simplechatchannelsPlayerData'
  tableNameII: 'simplechatchannelsIgnorelist'
