name: SimpleChatChannels
main: main.java.me.avankziar.scc.spigot.SimpleChatChannels
version: 41
author: Avankziar
api-version: 1.18
description: A Chat Plugin
softdepend: [AfkRecord, InterfaceHub]
website: https://www.spigotmc.org/resources/simple-chat-channels.35220/