name: SimpleChatChannels
main: main.java.me.avankziar.scc.spigot.SimpleChatChannels
version: 40
author: Avankziar
api-version: 1.16
description: A Chat Plugin
softdepend: [AfkRecord, InterfaceHub]