name: SimpleChatChannels
main: main.java.me.avankziar.simplechatchannels.spigot.SimpleChatChannels
version: 36
author: Avankziar
api-version: 1.15
description: A Chat Plugin
softdepend: [Punisher,AfkRecord]
commands:
  scc:
    description: A SCC Command
  clickchat:
    description: A ClickChat Command
    aliases: [clch]
  scceditor:
    description: A Scceditor Command
  msg:
    description: A Message Command
permissions:
  scc.channels.global:
    description: Enable global channel rights, to read and write and use /scc global.
    default: true
  scc.channels.trade:
    description: Enable trade channel rights, to read and write and use /scc trade.
    default: true
  scc.channels.auction:
    description: Enable auction channel rights, to read and write and use /scc auction.
    default: true
  scc.channels.event:
    description: Enable event channel rights, to read and write and use /scc auction.
    default: true
  scc.channels.local:
    description: Enable local channel rights, to read and write and use /scc local.
    default: true
  scc.channels.world:
    description: Enable world channel rights, to read and write and use /scc world.
    default: true
  scc.channels.support:
    description: Enable support channel rights, to read and write and use /scc support.
    default: true
  scc.channels.team:
    description: Enable team channel rights, to read and write and use /scc team.
    default: false
  scc.channels.admin:
    description: Enable admin channel rights, to read and write and use /scc admin.
    default: false
  scc.channels.temp:
    description: Enable temp channel rights, to read and write and use /scc temp.
    default: true
  scc.channels.perma:
    description: Enable permanent channel rights, to read and write and use /scc perma.
    default: true
  scc.channels.group:
    description: Enable group channel rights, to read and write and use /scc group.
    default: true
  scc.channels.pm:
    description: Enable pm channel rights, to read and write and use /scc pm.
    default: true
  scc.cmd.clickchat:
    description: Gives access to /clch <player> <Outputnumber> <message>.
    default: false
  scc.cmd.editor:
    description: Gives access to /scceditor, a mode which canceled all chat msg for SimpleChatChannels.
    default: false
  scc.option.admin:
    description: Gives access to /scc, which shows all commands. Without, it shows only commands that is important for players.
    default: false
  scc.option.spy:
    description: Gives access to /scc spy, which toggled your spy mode. Shows now all msg, as well private msg.
    default: false
  scc.option.join:
    description: Gives access to /scc join, which toggled whether you see server join messages.
    default: false
  scc.cmd.playerlist:
    description: Gives access to /scc playerlist [Search String], give you a list of onlineplayer (Bungee possible). Click on the name to show the @<player> in the chatline.  
    default: false
  scc.cmd.grouplist:
    description: Gives access to /scc grouplist [Search String], give you a list of all groups/Prefix/Suffix. Click on the name to show the @*<group> in the chatline.
    default: false
  scc.cmd.ignore:
    description: Gives access to /scc ignore <player>, which toggle whether you ignore the player.
    default: false
  scc.cmd.ignorelist:
    description: Gives access to /scc ignorlist, which shows you your list of ignored players.
    default: false
  scc.cmd.mute:
    description: Gives access to /scc mute <player> [min], mute a player for x minutes.
    default: false
  scc.cmd.unmute:
    description: Gives access to /scc unmute <player>, unmute the player.
    default: false
  scc.cmd.wordfilter:
    description: Gives access to /scc wordfilter <word>, a word from or to the wordfilter list.
    default: false
  scc.cmd.broadcast:
    description: Gives access to /scc broadcast <message>, to send a message to all onlineplayers (bungee/colorcode possible).
    default: false
  scc.cmd.reload:
    description: Gives access to /scc reload, to reload all yaml file on spigot level.
    default: false
  scc.cmd.tc.create:
    description: Gives access to /scc tccreate <name of channel> [password], create a temporary channel.
    default: false
  scc.cmd.tc.join:
    description: Gives access to /scc tcjoin <name of channel> [passwort], join a temporary channel.
    default: false
  scc.cmd.tc.info:
    description: Gives access to /scc tcinfo, gives all information from the temporary channel, in which you are in.
    default: false
  scc.cmd.tc.leave:
    description: Gives access to /scc tcleave, leave the temporary channel.
    default: false
  scc.cmd.tc.kick:
    description: Gives access to /scc tckick <player>, kick a player from your temporary channel.
    default: false
  scc.cmd.tc.ban:
    description: Gives access to /scc tcban <player>, ban a player from your temporary channel.
    default: false
  scc.cmd.tc.unban:
    description: Gives access to /scc tcunban <player>, unban a player from your temporary channel.
    default: false
  scc.cmd.tc.changepassword:
    description: Gives access to /scc tcchangepassword <password>, change a password for your temporary channel.
    default: false
  scc.cmd.tc.invite:
    description: Gives access to /scc tcinvite <Player>, to invite a player to your temporary channel.
    default: false
  scc.cmd.pc.ban:
    description: Gives access to /scc pcban <Channelname> <Player>, to ban a player from your permanent channel.
    default: false
  scc.cmd.pc.changepassword:
    description: Gives access to /scc pcchangepassword <Channelname> <Password>, to change the password from your permanent channel.
    default: false
  scc.cmd.pc.channels:
    description: Gives access to /scc pcchannels, to show all existing permanent channel.
    default: false
  scc.cmd.pc.chatcolor:
    description: Gives access to /scc pcchatcolor <Channelname> <ColorCode>, to change the Color which shows in the chat of your permanent channel.
    default: false
  scc.cmd.pc.create:
    description: Gives access to /scc pccreate <Channelname> [Password], to create your permanent channel.
    default: false
  scc.cmd.pc.delete:
    description: Gives access to /scc pcdelte <Channelname>, to delete a permanent channel. Admin Tool.
    default: false
  scc.cmd.pc.info:
    description: Gives access to /scc pcinfo <Channelname>, to show all info from the permanent channel.
    default: false
  scc.cmd.pc.inherit:
    description: Gives access to /scc pcinherit <Channelname> <Player>, to inherit a player as creator to the permanent channel. Admin Tool.
    default: false
  scc.cmd.pc.invite:
    description: Gives access to /scc pcinvite <Channelname> <Player>, to invite a player to your permanent channel.
    default: false
  scc.cmd.pc.join:
    description: Gives access to /scc pcjoin <Channelname> [Passsword], to join a permanent channel.
    default: false
  scc.cmd.pc.kick:
    description: Gives access to /scc pckick <Channelname> <Player>, to invite a player to your permanent channel.
    default: false
  scc.cmd.pc.leave:
    description: Gives access to /scc pcleave <Channelname>, to leave a permanent channel.
    default: false
  scc.cmd.pc.namecolor:
    description: Gives access to /scc pcnamecolor <Channelname> <ColorCode>, to change the color from the name prefox of your permanent channel.
    default: false
  scc.cmd.pc.player:
    description: Gives access to /scc pcplayer <Player>, to show all permanent channel which the player is in.
    default: false
  scc.cmd.pc.rename:
    description: Gives access to /scc pcrename <Channelname> <NewName>, to rename your permanent channel.
    default: false
  scc.cmd.pc.symbol:
    description: Gives access to /scc pcsymbol <Channelname> <Symbol>, to change the symbol, to access the permanent channel.
    default: false
  scc.cmd.pc.unban:
    description: Gives access to /scc pcunban <Channelname> <Player>, to pardon a player from your permanent channel.
    default: false
  scc.cmd.pc.vice:
    description: Gives access to /scc pcvice <Channelname> <Player>, to promote or demote a player as vice or member your permanent channel.
    default: false
  scc.channels.bypass.color:
    description: Gives access to use Color offside from the ChannelColor.
    default: false
  scc.channels.bypass.command:
    description: Gives access to use clickevent for commands in the chat. replacer => /<command>_<args1>_<args2>
    default: false
  scc.channels.bypass.ignore:
    description: Gives access to bypass the ignoring from a player.
    default: false
  scc.channels.bypass.item:
    description: Gives access to use hoverevent to show a item in the chat for the replacer <item>.
    default: false
  scc.channels.bypass.itemupload:
    description: Gives access to use hoverevent to show a item in the chat for the replacer <item>.
    default: false
  scc.channels.bypass.privacy:
    description: Gives access to bypass, if the targeted player has the private message channel off.
    default: false
  scc.channels.bypass.website:
    description: Gives access to add clickevent for websites in the chat.
    default: false
  scc.prefix.1:
    description: Gives access to prefix 1 for the chat.
    default: false
  scc.prefix.2:
    description: Gives access to prefix 2 for the chat.
    default: false
  scc.prefix.3:
    description: Gives access to prefix 3 for the chat.
    default: false
  scc.prefix.4:
    description: Gives access to prefix 4 for the chat.
    default: false
  scc.prefix.5:
    description: Gives access to prefix 5 for the chat.
    default: false
  scc.prefix.6:
    description: Gives access to prefix 6 for the chat.
    default: false
  scc.prefix.7:
    description: Gives access to prefix 7 for the chat.
    default: false
  scc.prefix.8:
    description: Gives access to prefix 8 for the chat.
    default: false
  scc.prefix.9:
    description: Gives access to prefix 9 for the chat.
    default: false
  scc.prefix.10:
    description: Gives access to prefix 10 for the chat.
    default: false
  scc.suffix.1:
    description: Gives access to suffix 1 for the chat.
    default: false
  scc.suffix.2:
    description: Gives access to suffix 2 for the chat.
    default: false
  scc.suffix.3:
    description: Gives access to suffix 3 for the chat.
    default: false
  scc.suffix.4:
    description: Gives access to suffix 4 for the chat.
    default: false
  scc.suffix.5:
    description: Gives access to suffix 5 for the chat.
    default: false
  scc.suffix.6:
    description: Gives access to suffix 6 for the chat.
    default: false
  scc.suffix.7:
    description: Gives access to suffix 7 for the chat.
    default: false
  scc.suffix.8:
    description: Gives access to suffix 8 for the chat.
    default: false
  scc.suffix.9:
    description: Gives access to suffix 9 for the chat.
    default: false
  scc.suffix.10:
    description: Gives access to suffix 10 for the chat.
    default: false
  