Language: 'English'
Prefix: '&7[&eS&6c&cc&7] &r'
Bungee: false
Denizen_Active: false
GetLocaleRadius: 50
WordFilter:
- arschloch
- asshole
AddingTimeOfDays: true
TimeOfDaysFormat: 'HH:mm'
TimeOfDaysOutput: '&7[%time%] &r'
UsePrefixForPlayerColor: true
ShowJoinMessageGlobal: false
ShowLeaveMessageGlobal: false
CCInviteCooldown: 60
Mysql:
  Status: false
  Host: '127.0.0.1'
  Port: 3306
  DatabaseName: 'mydatabase'
  SSLEnabled: false
  AutoReconnect: true
  VerifyServerCertificate: false
  User: 'admin'
  Password: 'not_0123456789'
  TableNameI: 'simplechatchannelsPlayerData'
  TableNameII: 'simplechatchannelsIgnorelist'
General:
  WorldNameReplaceInChannel: true