language: 'german'
bungee: 'false'
denizen_active: 'false'
getlocaleradius: 50
wordfilter:
- arschloch
- asshole
mysql:
  status: 'false'
  host: '127.0.0.1'
  port: '3306'
  databaseName: 'mydatabase'
  sslEnabled: 'false'
  autoReconnect: 'true'
  verifyServerCertificate: 'false'
  user: 'admin'
  password: 'not_0123456789'
  tableNameI: 'simplechatchannelsPlayerData'
  tableNameII: 'simplechatchannelsIgnorelist'
general:
  worldnamereplaceinchannel: 'true'